name: jfmt
description: A simple console application.
version: 1.0.0
homepage: https://github.com/kevmoo/jfmt
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

executables:
  jfmt:
